services:
  frontend:
    build: services/frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
  api:
    build: services/api
    restart: unless-stopped
    ports:
      - "4001:4000"
      - "8001:8000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
