import type { Metadata } from 'next';
import './globals.css';
import { Provider } from '@/components/ui/provider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return <html suppressHydrationWarning>
    <body>
    <Provider>
        {children}
    </Provider>
    </body>
    </html>;
}
